# Generated by Django 4.2.17 on 2025-01-10 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateTimeField()),
                ('design_type', models.TextField(choices=[('bedrooms', 'Bedroom'), ('washroom', 'Washroom'), ('kitchen', 'Kitchen'), ('livigroom', 'LivingRoom')])),
                ('confirmed', models.BooleanField(default=False)),
                ('message', models.TextField(max_length=500)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_of_booking'],
            },
        ),
    ]
