# Generated by Django 4.2.17 on 2025-01-09 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('appointment_date', models.DateTimeField()),
                ('design_style', models.TextField(choices=[('bedrooms', 'Bedroom'), ('washroom', 'Washroom'), ('kitchen', 'Kitchen'), ('livigroom', 'LivingRoom')])),
                ('notes', models.TextField(default='No notes provided')),
                ('confirmed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['appointment_date'],
            },
        ),
    ]
