# Generated by Django 4.2.17 on 2025-01-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(default='No notes provided'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='design_style',
            field=models.TextField(choices=[('bedrooms', 'Bedroom'), ('washroom', 'Washroom'), ('kitchen', 'Kitchen'), ('livigroom', 'LivingRoom')]),
        ),
    ]
