# Generated by Django 4.2.17 on 2025-01-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='location',
            new_name='address',
        ),
    ]
