# Generated by Django 4.2.17 on 2025-01-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_status_booking_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
    ]
