# Generated by Django 4.2.17 on 2025-01-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_location_booking_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='address',
            new_name='location',
        ),
    ]
